"""Build self-contained Windows and Mac download entries with Python's standard library."""
from pathlib import Path
import argparse
import datetime
import stat
import zipfile

SITE = Path(__file__).resolve().parent.parent
ASSETS = SITE / 'assets/localize'
SOURCE = SITE / 'scripts/localize'


def text(path):
    return path.read_text(encoding='utf-8-sig').replace('\r\n', '\n').rstrip() + '\n'


def entries():
    core = text(ASSETS / 'repair-i18n.cjs')
    mac = text(ASSETS / 'repair-i18n-mac.cjs')
    assert "\n'@\n" not in core
    base = text(ASSETS / 'codex-zh-cn.bat').split('\n# POWERSHELL-BEGIN\n', 1)[1]
    base = base.split('function Invoke-CodexChineseSetup {', 1)[0]
    header = '''@echo off
setlocal DisableDelayedExpansion
chcp 65001 >nul
set "TC_CODEX_REPAIR_SCRIPT=%~f0"
powershell.exe -NoLogo -NoProfile -STA -Command "$s=[IO.File]::ReadAllText($env:TC_CODEX_REPAIR_SCRIPT,[Text.Encoding]::UTF8); $p=($s -split '(?m)^# POWERSHELL-BEGIN\\r?$',2)[1]; & ([ScriptBlock]::Create($p))"
set "TC_CODEX_RESULT=%ERRORLEVEL%"
if not "%TC_CODEX_RESULT%"=="0" pause
exit /b %TC_CODEX_RESULT%
# POWERSHELL-BEGIN
# Generated by scripts/build-localize.py. Edit the sources, then rebuild.
'''
    windows = header + "$script:TiancaiCoreSource = @'\n" + core + "'@\n" + base + text(SOURCE / 'windows-repair.ps1')
    payloads = []
    for name, code in [('CORE', core), ('MAC', mac)]:
        marker = 'TIANCAI_' + name + '_PAYLOAD'
        assert '\n' + marker + '\n' not in code
        payloads.append(f": <<'{marker}'\n# TIANCAI BEGIN {name}\n{code}# TIANCAI END {name}\n{marker}\n")
    command = text(SOURCE / 'mac-entry.command.in').replace('@@EMBEDDED_PAYLOADS@@', '\n'.join(payloads)).rstrip() + '\n'
    return {
        '修复中文显示.bat': windows.replace('\n', '\r\n').encode('utf-8'),
        '修复中文显示.command': command.encode('utf-8'),
    }


def build(check=False):
    generated = entries()
    for name, data in generated.items():
        output = ASSETS / name
        if check:
            assert output.read_bytes() == data, f'Rebuild {name}'
        elif not output.exists() or output.read_bytes() != data:
            output.write_bytes(data)
    for archive_name, entry_name in [('codex-zh-cn-windows.zip', '修复中文显示.bat'), ('codex-zh-cn-mac.zip', '修复中文显示.command')]:
        output = ASSETS / archive_name
        mode = 0o755 if entry_name.endswith('.command') else 0o644
        def matches():
            if not output.exists():
                return False
            with zipfile.ZipFile(output) as archive:
                return (archive.testzip() is None and archive.namelist() == [entry_name]
                        and archive.read(entry_name) == generated[entry_name]
                        and (archive.getinfo(entry_name).external_attr >> 16) & 0o777 == mode)
        if check:
            assert matches(), f'Rebuild {archive_name}'
        elif not matches():
            info = zipfile.ZipInfo(entry_name, datetime.datetime.fromtimestamp((ASSETS / entry_name).stat().st_mtime).timetuple()[:6])
            info.create_system = 3
            info.external_attr = (stat.S_IFREG | mode) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            with zipfile.ZipFile(output, 'w') as archive:
                archive.writestr(info, generated[entry_name])
        print(f'{archive_name}: {entry_name}, {output.stat().st_size} bytes')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    build(parser.parse_args().check)
