@echo off
setlocal DisableDelayedExpansion
chcp 65001 >nul
set "TC_CODEX_REPAIR_SCRIPT=%~f0"
powershell.exe -NoLogo -NoProfile -STA -Command "$s=[IO.File]::ReadAllText($env:TC_CODEX_REPAIR_SCRIPT,[Text.Encoding]::UTF8); $p=($s -split '(?m)^# POWERSHELL-BEGIN\r?$',2)[1]; & ([ScriptBlock]::Create($p))"
set "TC_CODEX_RESULT=%ERRORLEVEL%"
if not "%TC_CODEX_RESULT%"=="0" pause
exit /b %TC_CODEX_RESULT%
# POWERSHELL-BEGIN
# Generated by scripts/build-localize.py. Edit the sources, then rebuild.
$script:TiancaiCoreSource = @'
'use strict';
// 添财AI：只在标记过的应用副本中启用内置翻译，不下载或执行应用脚本。
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawnSync } = require('node:child_process');
const MARKER = '/*TCZH2*/';
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
function requireCondition(ok, message) { if (!ok) throw new Error(message); }

function inspectTree(root) {
  root = path.resolve(root);
  const files = [], directories = [];
  function visit(relative) {
    const full = path.join(root, relative), info = fs.lstatSync(full);
    requireCondition(!info.isSymbolicLink(), '应用目录含有链接，停止复制：' + full);
    if (info.isDirectory()) {
      directories.push(relative);
      for (const name of fs.readdirSync(full).sort()) visit(path.join(relative, name));
    } else {
      requireCondition(info.isFile(), '应用目录含有不支持的文件类型：' + full);
      files.push({ relative, size: info.size });
    }
  }
  requireCondition(fs.lstatSync(root).isDirectory(), '应用路径不是目录：' + root);
  visit('');
  return { root, files, directories };
}

function treeSummary(tree) {
  const entries = [
    ...tree.directories.map(name => ['directory', name]),
    ...tree.files.map(file => ['file', file.relative, file.size])
  ];
  return { files: tree.files.length, directories: tree.directories.length,
    bytes: tree.files.reduce((total, file) => total + file.size, 0),
    manifestHash: sha(Buffer.from(JSON.stringify(entries))) };
}

function copyApplication(source, destination) {
  const tree = inspectTree(source);
  requireCondition(tree.files.length > 0, '原应用目录中没有文件，停止复制');
  destination = path.resolve(destination);
  // Resolve an existing parent before making any changes to either tree.
  destination = path.join(fs.realpathSync(path.dirname(destination)), path.basename(destination));
  const relative = path.relative(fs.realpathSync(tree.root), destination);
  requireCondition(relative && (relative === '..' || relative.startsWith('..' + path.sep) || path.isAbsolute(relative)), '副本目录不能位于原应用目录内');
  // A fresh destination is required; never merge into or overwrite an existing copy.
  fs.mkdirSync(destination);
  for (const name of tree.directories) if (name) fs.mkdirSync(path.join(destination, name), { recursive: true });
  const buffer = Buffer.alloc(1024 * 1024);
  for (const file of tree.files) {
    let input, output;
    try {
      input = fs.openSync(path.join(tree.root, file.relative), 'r');
      output = fs.openSync(path.join(destination, file.relative), 'wx');
      let copied = 0, length;
      // Copy bytes only, without inheriting WindowsApps encryption or file attributes.
      while ((length = fs.readSync(input, buffer, 0, buffer.length, null)) > 0) {
        let offset = 0;
        while (offset < length) {
          const written = fs.writeSync(output, buffer, offset, length - offset);
          requireCondition(written > 0, '文件写入未完成');
          offset += written;
        }
        copied += length;
      }
      requireCondition(copied === file.size && fs.fstatSync(output).size === file.size, '复制前后大小不一致，原文件可能正在更新');
    } catch (error) {
      throw new Error('复制文件失败：' + file.relative + '；' + error.message);
    } finally {
      if (output !== undefined) fs.closeSync(output);
      if (input !== undefined) fs.closeSync(input);
    }
  }
  let result;
  try { result = treeSummary(inspectTree(destination)); }
  catch (error) { throw new Error('核对副本失败：' + error.message); }
  requireCondition(result.manifestHash === treeSummary(tree).manifestHash, '复制后的文件清单或大小不一致，停止修复');
  return result;
}

function readArchive(file) {
  const fd = fs.openSync(file, 'r');
  try {
    const length = fs.fstatSync(fd).size;
    const prefix = Buffer.alloc(16);
    requireCondition(fs.readSync(fd, prefix, 0, 16, 0) === 16, 'ASAR 文件头不完整');
    const jsonSize = prefix.readUInt32LE(12), start = 8 + prefix.readUInt32LE(4);
    requireCondition(jsonSize > 0 && jsonSize < 32 * 1024 * 1024 && start >= 16 + jsonSize && start <= length, 'ASAR 文件头范围无效');
    const bytes = Buffer.alloc(jsonSize);
    requireCondition(fs.readSync(fd, bytes, 0, jsonSize, 16) === jsonSize, '无法读取完整 ASAR 文件头');
    const text = bytes.toString('utf8'), header = JSON.parse(text), entries = new Map();
    function visit(node, prefix = '') {
      for (const [name, entry] of Object.entries(node.files || {})) {
        const key = prefix + name;
        if (entry.files) visit(entry, key + '/');
        else entries.set(key, entry);
      }
    }
    visit(header);
    function read(name) {
      const entry = entries.get(name), offset = Number(entry?.offset), size = entry?.size;
      requireCondition(entry && !entry.unpacked && !entry.link && Number.isSafeInteger(size) && size >= 0 && Number.isSafeInteger(offset) && offset >= 0 && start + offset + size <= length, '不支持的 ASAR 文件条目：' + name);
      requireCondition(size <= 64 * 1024 * 1024, '应用脚本过大，停止自动修补：' + name);
      const content = Buffer.alloc(size);
      requireCondition(fs.readSync(fd, content, 0, size, start + offset) === size, '应用文件读取不完整：' + name);
      return content;
    }
    return { fd, header, text, bytes, start, entries, read, close: () => fs.closeSync(fd) };
  } catch (error) { fs.closeSync(fd); throw error; }
}

function patchSource(source) {
  // Match only the known i18n boolean getter; other experiment settings are untouched.
  const calls = [...source.matchAll(/\.get\(\s*([`"'])enable_i18n\1\s*,/g)].length;
  const getter = /(?<![\w$.?])[$A-Z_a-z][\w$]*(?:\(\s*([`"'])72216192\1\s*\))?(?:\?\.|\.)get\(\s*([`"'])enable_i18n\2\s*,\s*(?:![01]|true|false)\s*\)/g;
  let count = 0;
  const code = source.replace(getter, match => {
    count++;
    return ('true' + MARKER).padEnd(match.length, ' ');
  });
  requireCondition(count === calls, '国际化代码结构已变化，停止自动修补');
  return { code, count };
}

function inspectRuntime(root, headerHash) {
  const sentinel = Buffer.from('dL7pKGdnNz796PbbjQWNKmHXBZaB9tsX');
  let fuseState;
  for (const name of ['ChatGPT.exe', 'Codex.exe', 'chrome.dll']) {
    const file = path.join(root, name);
    if (!fs.existsSync(file)) continue;
    const bytes = fs.readFileSync(file), offset = bytes.indexOf(sentinel);
    if (offset < 0) continue;
    requireCondition(bytes.indexOf(sentinel, offset + 1) < 0, '完整性校验标记不唯一：' + name);
    const wire = offset + sentinel.length;
    requireCondition(bytes[wire] === 1 && bytes[wire + 1] >= 5 && wire + 2 + bytes[wire + 1] <= bytes.length, '无法识别此版本的完整性校验格式');
    const state = bytes[wire + 6]; // Fuse V1 index 4: EmbeddedAsarIntegrityValidation.
    requireCondition(state === 48 || state === 49, '不支持的完整性校验状态');
    requireCondition(fuseState === undefined || fuseState === state, '检测到不同的完整性校验状态');
    fuseState = state;
  }
  requireCondition(fuseState !== undefined, '无法识别应用运行时，请提供版本和诊断记录');
  if (fuseState === 48) return { mode: '校验开关原本关闭；保留可执行文件', patches: [] };
  const patches = [];
  for (const name of ['ChatGPT.exe', 'Codex.exe']) {
    const file = path.join(root, name);
    if (!fs.existsSync(file)) continue;
    const bytes = fs.readFileSync(file);
    for (const encoding of ['utf8', 'utf16le']) for (const upper of [false, true]) {
      const needle = Buffer.from(upper ? headerHash.toUpperCase() : headerHash, encoding);
      let offset = bytes.indexOf(needle);
      while (offset >= 0) {
        patches.push({ name, offset, encoding, upper, length: needle.length });
        offset = bytes.indexOf(needle, offset + needle.length);
      }
    }
  }
  requireCondition(patches.length > 0, '完整性校验已开启，但未找到匹配的原始哈希；停止修补');
  return { mode: '保留完整性校验并更新副本哈希', patches };
}

function planArchive(file) {
  const archive = readArchive(file);
  try {
    const metadata = JSON.parse(archive.read('package.json'));
    requireCondition(metadata.name === 'openai-codex-electron', '所选目录不是支持的 Codex 桌面应用');
    const chinese = [...archive.entries.keys()].filter(name => /^webview\/assets\/zh-CN(?:-[\w-]+)?\.(?:js|json)$/.test(name));
    requireCondition(chinese.length > 0, '没有找到内置中文翻译文件，请先更新安装包');
    for (const name of chinese) {
      const bytes = archive.read(name), entry = archive.entries.get(name);
      requireCondition(bytes.length > 0 && entry.integrity?.algorithm === 'SHA256' && sha(bytes) === entry.integrity.hash, '中文翻译文件不完整，请重新安装原始安装包：' + name);
    }
    const changes = [];
    let providerCount = 0, already = 0;
    for (const name of archive.entries.keys()) {
      if (!/^webview\/assets\/[^/]+\.js$/.test(name)) continue;
      const original = archive.read(name), source = original.toString('utf8');
      if (source.includes(MARKER)) already++;
      if (!source.includes('enable_i18n')) continue;
      const changed = patchSource(source);
      if (!changed.count) continue;
      if (source.includes('Failed to load locale messages')) providerCount++;
      const replacement = Buffer.from(changed.code);
      requireCondition(replacement.length === original.length, '修补会改变文件长度，已停止：' + name);
      const syntax = spawnSync(process.execPath, ['--check', '--input-type=module'], { input: replacement, encoding: 'utf8', timeout: 30000, windowsHide: true });
      requireCondition(syntax.status === 0, '修补后 JavaScript 语法检查失败：' + name);
      const entry = archive.entries.get(name), integrity = entry.integrity;
      requireCondition(integrity?.algorithm === 'SHA256' && integrity.hash === sha(original), '原始脚本完整性检查失败：' + name);
      const blockSize = integrity.blockSize;
      requireCondition(Number.isSafeInteger(blockSize) && blockSize > 0 && Array.isArray(integrity.blocks) && integrity.blocks.length === Math.ceil(original.length / blockSize), '不支持的文件分块校验格式：' + name);
      const blocks = [];
      for (let i = 0; i < original.length; i += blockSize) {
        requireCondition(integrity.blocks[i / blockSize] === sha(original.subarray(i, i + blockSize)), '原始文件分块校验失败：' + name);
        blocks.push(sha(replacement.subarray(i, i + blockSize)));
      }
      entry.integrity = { ...integrity, hash: sha(replacement), blocks };
      changes.push({ name, count: changed.count, offset: archive.start + Number(entry.offset), content: replacement });
    }
    requireCondition(already === 0, '所选来源已经是添财AI修复副本，请直接使用修复版快捷方式，或选择原安装目录');
    requireCondition(providerCount === 1 && changes.length > 0, '未找到唯一、受支持的翻译加载入口，停止自动修补');
    const nextHeader = Buffer.from(JSON.stringify(archive.header));
    requireCondition(nextHeader.length === archive.bytes.length, 'ASAR 文件头格式发生变化，停止自动修补');
    const oldHash = sha(archive.bytes), newHash = sha(nextHeader);
    return { version: metadata.version, chinese, changes, nextHeader, oldHash, newHash };
  } finally { archive.close(); }
}

function plan(root) {
  const result = planArchive(path.join(root, 'resources', 'app.asar'));
  return { ...result, runtime: inspectRuntime(root, result.oldHash) };
}

function writeArchive(asar, result) {
  const before = readArchive(asar);
  try { requireCondition(sha(before.bytes) === result.oldHash, '写入前应用资源已变化，请重新运行'); }
  finally { before.close(); }
  const fd = fs.openSync(asar, 'r+');
  try {
    for (const item of result.changes) requireCondition(fs.writeSync(fd, item.content, 0, item.content.length, item.offset) === item.content.length, '脚本写入不完整');
    requireCondition(fs.writeSync(fd, result.nextHeader, 0, result.nextHeader.length, 16) === result.nextHeader.length, '文件头写入不完整');
    fs.fsyncSync(fd);
  } finally { fs.closeSync(fd); }
  const verified = readArchive(asar);
  try {
    requireCondition(sha(verified.bytes) === result.newHash, '修补后的文件头校验失败');
    for (const item of result.changes) {
      const content = verified.read(item.name), entry = verified.entries.get(item.name);
      requireCondition(content.equals(item.content) && sha(content) === entry.integrity.hash, '修补后文件校验失败：' + item.name);
    }
  } finally { verified.close(); }
}

function patchCopy(root) {
  const realRoot = fs.realpathSync(root);
  const markerPath = path.join(realRoot, '.tiancai-i18n-copy.json');
  const marker = JSON.parse(fs.readFileSync(markerPath, 'utf8').replace(/^\uFEFF/, ''));
  requireCondition(marker.tool === 'tiancai-i18n-2' && path.resolve(marker.source).toLowerCase() !== realRoot.toLowerCase(), '只能修补添财AI创建的独立应用副本');
  requireCondition(!realRoot.toLowerCase().includes('\\windowsapps\\'), '不允许修改 WindowsApps 中的安装文件');
  const result = plan(realRoot);
  requireCondition(result.oldHash === marker.sourceHeaderHash, '复制后的应用资源与检查时不一致，请重新运行');
  const asar = path.join(realRoot, 'resources', 'app.asar');
  // The source installation is the recovery copy. Failed builds receive no shortcut.
  writeArchive(asar, result);
  for (const item of result.runtime.patches) {
    const hash = item.upper ? result.newHash.toUpperCase() : result.newHash;
    const bytes = Buffer.from(hash, item.encoding);
    const fd = fs.openSync(path.join(realRoot, item.name), 'r+');
    try { requireCondition(fs.writeSync(fd, bytes, 0, bytes.length, item.offset) === bytes.length, '可执行文件校验值写入失败'); fs.fsyncSync(fd); }
    finally { fs.closeSync(fd); }
  }
  for (const item of result.runtime.patches) {
    const exe = fs.readFileSync(path.join(realRoot, item.name));
    requireCondition(exe.subarray(item.offset, item.offset + item.length).toString(item.encoding).toLowerCase() === result.newHash, '应用完整性哈希复核失败');
  }
  fs.writeFileSync(markerPath, JSON.stringify({ ...marker, patched: true, headerHash: result.newHash, files: result.changes.map(x => x.name) }, null, 2));
  return result;
}

function summary(result) {
  return { version: result.version, chineseResources: result.chinese.length, patchedGetters: result.changes.reduce((n, x) => n + x.count, 0), files: result.changes.map(x => x.name), headerHash: result.oldHash, newHeaderHash: result.newHash, integrity: result.runtime.mode };
}
module.exports = { inspectTree, treeSummary, copyApplication, readArchive, patchSource, planArchive, writeArchive, inspectRuntime, plan, patchCopy, summary };
if (require.main === module) {
  try {
    const [mode, root, destination] = process.argv.slice(2);
    requireCondition(root && ['inspect', 'patch-copy', 'inspect-tree', 'copy-app'].includes(mode), '用法：repair-i18n.cjs inspect|patch-copy|inspect-tree|copy-app 应用目录 [新副本目录]');
    requireCondition(mode !== 'copy-app' || destination, '复制应用时必须指定新副本目录');
    const result = mode === 'inspect-tree' ? treeSummary(inspectTree(root))
      : mode === 'copy-app' ? copyApplication(root, destination)
      : summary(mode === 'inspect' ? plan(root) : patchCopy(root));
    process.stdout.write(JSON.stringify(result));
  } catch (error) { process.stderr.write(error.message + '\n'); process.exitCode = 1; }
}
'@
# 添财AI：只切换 Codex 桌面版界面语言。无需管理员权限，不下载或运行外部代码。

function ConvertTo-CodexChineseConfig {
    param([AllowEmptyString()][string]$Text)
    $newline = if ($Text.Contains("`r`n")) { "`r`n" } else { "`n" }
    $rows = New-Object 'System.Collections.Generic.List[string]'
    foreach ($row in ($Text -split '\r?\n')) { $rows.Add($row) }
    $desktopKey = '(?:desktop|"desktop"|''desktop'')'
    $localeKey = '(?:localeOverride|"localeOverride"|''localeOverride'')'
    $inDesktop = $false; $root = $true; $header = -1; $firstHeader = -1
    $localeLine = -1; $rootDotted = $false; $multi = ''; $depth = 0
    $replacementKey = 'localeOverride'
    for ($lineNo = 0; $lineNo -lt $rows.Count; $lineNo++) {
        $line = $rows[$lineNo]
        $eligible = $multi -eq '' -and $depth -eq 0
        if ($eligible) {
            if ($line -cmatch ('^\s*\[\s*' + $desktopKey + '\s*\]\s*(?:#.*)?$')) {
                if ($header -ge 0) { throw '检测到重复的 [desktop]，原配置不会改动。请先修复配置。' }
                $header = $lineNo; $inDesktop = $true; $root = $false
                if ($firstHeader -lt 0) { $firstHeader = $lineNo }
            } elseif ($line -cmatch '^\s*\[') {
                $inDesktop = $false; $root = $false
                if ($firstHeader -lt 0) { $firstHeader = $lineNo }
            }
            if ($root -and $line -cmatch ('^\s*' + $desktopKey + '\s*=')) {
                throw '检测到 desktop 内联配置，请在 Codex 的语言设置中调整。原配置不会改动。'
            }
            if ($root -and $line -cmatch ('^\s*' + $desktopKey + '\s*\.')) { $rootDotted = $true }
            $localMatch = $inDesktop -and $line -cmatch ('^\s*' + $localeKey + '\s*=')
            $dottedMatch = $root -and $line -cmatch ('^\s*' + $desktopKey + '\s*\.\s*' + $localeKey + '\s*=')
            if ($localMatch -or $dottedMatch) {
                if ($localeLine -ge 0) { throw '检测到重复的语言配置，原配置不会改动。' }
                $localeLine = $lineNo
                if ($dottedMatch) { $replacementKey = 'desktop.localeOverride' }
            }
        }
        # 跳过注释、引号、多行字符串和数组中的内容，避免把示例文字当成设置。
        $quote = ''; $i = 0
        while ($i -lt $line.Length) {
            $char = [string]$line[$i]
            if ($multi -ne '') {
                if ($multi -eq '"' -and $char -eq '\') { $i += 2; continue }
                if ($i + 2 -lt $line.Length -and $line.Substring($i, 3) -ceq ($multi * 3)) {
                    $closing = $multi; $multi = ''
                    while ($i -lt $line.Length -and [string]$line[$i] -ceq $closing) { $i++ }
                    continue
                }
            } elseif ($quote -ne '') {
                if ($quote -eq '"' -and $char -eq '\') { $i += 2; continue }
                if ($char -ceq $quote) { $quote = '' }
            } else {
                if ($char -eq '#') { break }
                if ($char -eq '"' -or $char -eq "'") {
                    if ($i + 2 -lt $line.Length -and $line.Substring($i, 3) -ceq ($char * 3)) {
                        $multi = $char; $i += 3; continue
                    }
                    $quote = $char
                } elseif ($char -eq '[' -or $char -eq '{') { $depth++ }
                elseif ($char -eq ']' -or $char -eq '}') { $depth-- }
            }
            $i++
        }
        if ($quote -ne '' -or $depth -lt 0) { throw '配置中的引号或括号不完整，原文件不会改动。' }
        if ($localeLine -eq $lineNo -and ($multi -ne '' -or $depth -ne 0)) {
            throw '语言字段使用了多行写法，请在 Codex 设置中调整。原配置不会改动。'
        }
    }
    if ($multi -ne '' -or $depth -ne 0) { throw '配置中的多行字符串或数组未结束，原文件不会改动。' }
    if ($localeLine -ge 0) {
        $old = $rows[$localeLine]
        if ($old -cmatch '^([^=]+=\s*)(?:"[^"\r\n]*"|''[^''\r\n]*'')(\s*(?:#.*)?)$') {
            $rows[$localeLine] = $Matches[1] + '"zh-CN"' + $Matches[2]
        } else {
            $rows[$localeLine] = [regex]::Match($old, '^\s*').Value + $replacementKey + ' = "zh-CN"'
        }
    } elseif ($header -ge 0) {
        $rows.Insert($header + 1, 'localeOverride = "zh-CN"')
    } elseif ($rootDotted) {
        $position = if ($firstHeader -ge 0) { $firstHeader } else { $rows.Count }
        $rows.Insert($position, 'desktop.localeOverride = "zh-CN"')
    } else {
        if ($rows.Count -gt 0 -and $rows[$rows.Count - 1] -ne '') { $rows.Add('') }
        $rows.Add('[desktop]'); $rows.Add('localeOverride = "zh-CN"'); $rows.Add('')
    }
    return [string]::Join($newline, $rows)
}

function Set-CodexChineseConfig {
    param([string]$ConfigPath)
    $ConfigPath = [IO.Path]::GetFullPath($ConfigPath)
    $exists = [IO.File]::Exists($ConfigPath)
    if (Test-Path -LiteralPath $ConfigPath) {
        $item = Get-Item -LiteralPath $ConfigPath -Force
        if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
            throw '配置路径是目录或链接，请手动设置语言，避免影响原文件。'
        }
    }
    $utf8 = New-Object Text.UTF8Encoding($false, $true)
    [byte[]]$original = @(if ($exists) { [IO.File]::ReadAllBytes($ConfigPath) })
    $text = $utf8.GetString($original).TrimStart([char]0xFEFF)
    $updated = ConvertTo-CodexChineseConfig $text
    if ($exists -and $updated -ceq $text) { return [pscustomobject]@{ Changed = $false; Backup = '' } }
    $directory = [IO.Path]::GetDirectoryName($ConfigPath)
    [void][IO.Directory]::CreateDirectory($directory)
    $tag = (Get-Date -Format 'yyyyMMdd-HHmmss-fff') + '-' + [guid]::NewGuid().ToString('N').Substring(0, 6)
    $backup = ''
    $temporary = Join-Path $directory ('.config.toml.zh-cn.' + $tag + '.tmp')
    try {
        [IO.File]::WriteAllText($temporary, $updated, $utf8)
        if ($exists) {
            if ([Convert]::ToBase64String([IO.File]::ReadAllBytes($ConfigPath)) -cne [Convert]::ToBase64String($original)) {
                throw '配置刚刚被其他程序修改，请关闭 Codex 后重新运行。'
            }
            $backup = $ConfigPath + '.before-zh-cn.' + $tag + '.bak'
            [IO.File]::Replace($temporary, $ConfigPath, $backup)
        } else { [IO.File]::Move($temporary, $ConfigPath) }
    } finally {
        if ([IO.File]::Exists($temporary)) { [IO.File]::Delete($temporary) }
    }
    return [pscustomobject]@{ Changed = $true; Backup = $backup }
}

function Get-CodexAppInfo {
    param([string]$Executable, [string]$Activation = '')
    $ErrorActionPreference = 'Stop'
    # Only read the archive header and package identity. No application code is executed.
    if (-not [IO.File]::Exists($Executable)) { return }
    $Executable = [IO.Path]::GetFullPath($Executable)
    $archivePath = Join-Path ([IO.Path]::GetDirectoryName($Executable)) 'resources\app.asar'
    if (-not [IO.File]::Exists($archivePath)) { return }
    $stream = $null; $reader = $null
    try {
        $stream = [IO.File]::Open($archivePath, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::ReadWrite)
        $reader = New-Object IO.BinaryReader($stream)
        $prefix = $reader.ReadBytes(16)
        if ($prefix.Length -ne 16) { return }
        $headerSize = [BitConverter]::ToUInt32($prefix, 4)
        $jsonLength = [BitConverter]::ToUInt32($prefix, 12)
        if ($jsonLength -lt 2 -or $jsonLength -gt 33554432 -or $headerSize -lt $jsonLength + 8 -or 8L + $headerSize -gt $stream.Length) { return }
        $headerBytes = $reader.ReadBytes([int]$jsonLength)
        if ($headerBytes.Length -ne $jsonLength) { return }
        $header = [Text.Encoding]::UTF8.GetString($headerBytes) | ConvertFrom-Json
        $entry = $header.files.'package.json'
        if (-not $entry -or $entry.unpacked -or $entry.size -lt 2 -or $entry.size -gt 1048576) { return }
        $position = 8L + $headerSize + [long]$entry.offset
        if ($position -lt 8L + $headerSize -or $position + [long]$entry.size -gt $stream.Length) { return }
        [void]$stream.Seek($position, [IO.SeekOrigin]::Begin)
        $metadata = [Text.Encoding]::UTF8.GetString($reader.ReadBytes([int]$entry.size)) | ConvertFrom-Json
        if ($metadata.name -cne 'openai-codex-electron') { return }
        $assets = $header.files.webview.files.assets.files
        $chineseEntries = @($assets.PSObject.Properties | Where-Object { $_.Name -cmatch '^zh-CN(?:-[A-Za-z0-9_-]+)?\.(?:js|json)$' -and $_.Value.size -gt 0 })
        $nativeEntry = $header.files.'native-menu-locales'.files.'zh-CN.json'
        return [pscustomobject]@{
            Executable = $Executable; Activation = $Activation; Version = [string]$metadata.version
            ChineseResource = ($chineseEntries.Count -gt 0); NativeChineseResource = ($null -ne $nativeEntry)
        }
    } catch { return }
    finally { if ($reader) { $reader.Dispose() } elseif ($stream) { $stream.Dispose() } }
}

function Get-CodexGuiProcesses {
    param([string]$Executable)
    Get-Process -Name Codex,ChatGPT -ErrorAction SilentlyContinue | Where-Object {
        try { $_.Path -and $_.Path.Equals($Executable, [StringComparison]::OrdinalIgnoreCase) } catch { $false }
    }
}

function Resolve-CodexApp {
    $apps = @{}
    foreach ($package in @(Get-AppxPackage -Name OpenAI.Codex -ErrorAction SilentlyContinue)) {
        try {
            [xml]$manifest = [IO.File]::ReadAllText((Join-Path $package.InstallLocation 'AppxManifest.xml'))
            $entry = @($manifest.Package.Applications.Application) | Where-Object { $_.Executable -match '(?:Codex|ChatGPT)\.exe$' } | Select-Object -First 1
            if (-not $entry) { continue }
            $app = Get-CodexAppInfo (Join-Path $package.InstallLocation ([string]$entry.Executable)) ('shell:AppsFolder\' + $package.PackageFamilyName + '!' + $entry.Id)
            if ($app) { $apps[$app.Executable] = $app }
        } catch { }
    }
    $runningPaths = @(Get-Process -Name Codex,ChatGPT -ErrorAction SilentlyContinue | ForEach-Object { try { if ($_.Path) { $_.Path } } catch { } } | Sort-Object -Unique)
    $paths = @($runningPaths)
    foreach ($root in @((Join-Path $env:LOCALAPPDATA 'Programs\Codex'), (Join-Path $env:ProgramFiles 'Codex'))) {
        $paths += Join-Path $root 'ChatGPT.exe'
        $paths += Join-Path $root 'Codex.exe'
    }
    foreach ($path in @($paths | Sort-Object -Unique)) {
        if ($apps.ContainsKey($path)) { continue }
        $app = Get-CodexAppInfo $path
        if ($app) { $apps[$app.Executable] = $app }
    }
    $running = @($apps.Values | Where-Object { $runningPaths -contains $_.Executable })
    if ($running.Count -eq 1) { return $running[0] }
    $choices = @($apps.Values | Sort-Object Executable)
    if ($choices.Count -eq 1) { return $choices[0] }
    if ($choices.Count -gt 1) {
        Write-Host '发现多份 Codex，请在弹出的窗口中选择原版应用的 ChatGPT.exe 或 Codex.exe。'
    } else {
        Write-Host '请在弹出的窗口中选择已安装的 Codex：ChatGPT.exe 或 Codex.exe。'
    }
    Add-Type -AssemblyName System.Windows.Forms
    $picker = New-Object Windows.Forms.OpenFileDialog
    $picker.Title = '选择原版 Codex，不要选择中文修复副本'
    $picker.Filter = 'Codex 应用 (ChatGPT.exe; Codex.exe)|ChatGPT.exe;Codex.exe'
    if ($choices.Count) { $picker.InitialDirectory = [IO.Path]::GetDirectoryName($choices[0].Executable) }
    try {
        if ($picker.ShowDialog() -eq [Windows.Forms.DialogResult]::OK) {
            $app = Get-CodexAppInfo $picker.FileName
            if ($app) { return $app }
        }
    } finally { $picker.Dispose() }
    throw '未识别到 Codex 桌面应用，配置尚未修改。请先安装或打开 Codex，再运行脚本。'
}

function Wait-CodexGuiState {
    param([string]$Executable, [bool]$Running, [int]$Seconds = 10)
    $timer = [Diagnostics.Stopwatch]::StartNew()
    do {
        $present = @(Get-CodexGuiProcesses $Executable).Count -gt 0
        if ($present -eq $Running) { return $true }
        Start-Sleep -Milliseconds 250
    } while ($timer.Elapsed.TotalSeconds -lt $Seconds)
    return $false
}

# 添财AI · Windows 中文显示修复 3.0：单文件入口，自动修复。

function Copy-CodexNodeRuntime {
    param([string]$Source)
    $directory = Join-Path ([IO.Path]::GetTempPath()) ('TiancaiAI-Codex-Node-' + [guid]::NewGuid().ToString('N'))
    [void][IO.Directory]::CreateDirectory($directory)
    $destination = Join-Path $directory 'node.exe'
    $inputFile = $null; $outputFile = $null; $copied = $false
    try {
        # Copy bytes instead of package attributes or encryption metadata.
        $inputFile = [IO.File]::OpenRead($Source)
        $outputFile = [IO.File]::Open($destination, [IO.FileMode]::CreateNew, [IO.FileAccess]::Write)
        $inputFile.CopyTo($outputFile)
        $copied = $true
    } finally {
        if ($outputFile) { $outputFile.Dispose() }
        if ($inputFile) { $inputFile.Dispose() }
        if (-not $copied) { try { [IO.File]::Delete($destination); [IO.Directory]::Delete($directory) } catch { } }
    }
    return [pscustomobject]@{ Directory=$directory; Executable=$destination }
}

function Invoke-I18nHelper {
    param([string]$Node, [string]$Helper, [string]$Mode, [string]$AppRoot, [string]$Destination)
    [Console]::OutputEncoding = New-Object Text.UTF8Encoding($false)
    $helperArgs = @($Helper, $Mode, $AppRoot)
    if ($Destination) { $helperArgs += $Destination }
    $lines = @(& $Node @helperArgs 2>&1)
    if ($LASTEXITCODE -ne 0) { throw ('应用处理失败：' + ($lines -join "`n")) }
    return (($lines -join "`n") | ConvertFrom-Json)
}

function New-ChineseCopyLauncher {
    param([string]$CopyRoot, [string]$Executable, [string]$CodexHome, [string]$UserData)
    $launcher = Join-Path $CopyRoot '启动修复版.vbs'
    $template = @'
Option Explicit
Dim shell, env, exe, command
Set shell = CreateObject("WScript.Shell")
Set env = shell.Environment("PROCESS")
exe = "__EXE__"
env("CODEX_HOME") = "__HOME__"
env("CODEX_ELECTRON_USER_DATA_PATH") = "__DATA__"
env("ELECTRON_LOCALE_OVERRIDE") = "zh-CN"
command = Chr(34) & exe & Chr(34) & " --lang=zh-CN"
shell.Run command, 1, False
'@
    $template = $template.Replace('__EXE__', $Executable.Replace('"', '""')).Replace('__HOME__', $CodexHome.Replace('"', '""')).Replace('__DATA__', $UserData.Replace('"', '""'))
    [IO.File]::WriteAllText($launcher, $template, [Text.Encoding]::Unicode)
    $desktop = [Environment]::GetFolderPath('Desktop')
    if (-not $desktop) { throw '无法找到桌面目录，未创建快捷方式。' }
    $shortcutPath = Join-Path $desktop 'Codex 中文修复版（添财AI）.lnk'
    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($shortcutPath)
    $shortcut.TargetPath = Join-Path $env:WINDIR 'System32\wscript.exe'
    $shortcut.Arguments = '"' + $launcher + '"'
    $shortcut.WorkingDirectory = $CopyRoot
    $shortcut.IconLocation = "$Executable,0"
    $shortcut.Description = '添财AI · 启用 Codex 内置翻译的独立副本'
    $shortcut.Save()
    return [pscustomobject]@{ Launcher=$launcher; Shortcut=$shortcutPath }
}

function Invoke-CodexChineseRepair {
    $ErrorActionPreference = 'Stop'
    $phase = '读取工具'; $copyRoot = ''; $sourceApp = $null; $restoreOriginal = $false; $exitCode = 0; $runtime = $null
    $report = New-Object 'System.Collections.Generic.List[string]'
    $report.Add('添财AI · Windows 中文显示修复 3.0')
    $report.Add('时间：' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
    $report.Add('Windows 版本：' + [Environment]::OSVersion.VersionString)
    $report.Add('PowerShell 版本：' + $PSVersionTable.PSVersion.ToString())
    try {
        Write-Host '添财AI · Windows 中文显示修复 3.0' -ForegroundColor Green
        $phase = '检查原安装'
        Write-Host '[1/3] 正在检查 Codex……'
        $sourceApp = Resolve-CodexApp
        $sourceRoot = [IO.Path]::GetDirectoryName($sourceApp.Executable)
        $node = Join-Path $sourceRoot 'resources\cua_node\bin\node.exe'
        if (-not [IO.File]::Exists($node)) { throw '该版本没有所需的内置 Node.js，请先更新 Codex；无需自行安装开发工具。' }
        $runtime = Copy-CodexNodeRuntime $node
        $node = $runtime.Executable
        $helper = Join-Path $runtime.Directory 'repair-i18n.cjs'
        [IO.File]::WriteAllText($helper, $script:TiancaiCoreSource, (New-Object Text.UTF8Encoding($false)))
        $inspection = Invoke-I18nHelper $node $helper 'inspect' $sourceRoot
        $report.Add('原应用：' + $sourceApp.Executable)
        $report.Add('应用版本：' + $inspection.version)
        $report.Add('中文资源数：' + $inspection.chineseResources)
        $report.Add('待修复的国际化开关数：' + $inspection.patchedGetters)
        $report.Add('完整性处理：' + $inspection.integrity)
        $phase = '统计原应用文件'
        $sourceTree = Invoke-I18nHelper $node $helper 'inspect-tree' $sourceRoot
        $bytes = $sourceTree.bytes
        if ($sourceTree.files -lt 1) { throw '原应用目录中没有文件，停止复制。' }
        $report.Add('原应用文件数：' + $sourceTree.files + '；总字节数：' + $bytes)
        $baseRoot = [IO.Path]::GetFullPath((Join-Path $env:LOCALAPPDATA 'TiancaiAI\CodexChinese'))
        $disk = New-Object IO.DriveInfo([IO.Path]::GetPathRoot($baseRoot))
        if ($disk.AvailableFreeSpace -lt $bytes + 104857600) { throw '磁盘空间不足，需要额外保存一份 Codex 应用。' }
        $codexHome = if ([string]::IsNullOrWhiteSpace($env:CODEX_HOME)) { Join-Path ([Environment]::GetFolderPath('UserProfile')) '.codex' } else { $env:CODEX_HOME }
        $codexHome = [IO.Path]::GetFullPath($codexHome)
        $configPath = Join-Path $codexHome 'config.toml'
        if ([IO.File]::Exists($configPath)) { [void](ConvertTo-CodexChineseConfig ([IO.File]::ReadAllText($configPath, [Text.Encoding]::UTF8))) }
        $report.Add('副本空间需求约 ' + [Math]::Ceiling($bytes / 1MB) + ' MB')
        $phase = '复制应用'
        $copyRoot = [IO.Path]::GetFullPath((Join-Path $baseRoot ('build-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '-' + [guid]::NewGuid().ToString('N').Substring(0, 6))))
        if (-not $copyRoot.StartsWith($baseRoot.TrimEnd('\') + '\', [StringComparison]::OrdinalIgnoreCase) -or $copyRoot.StartsWith($sourceRoot.TrimEnd('\') + '\', [StringComparison]::OrdinalIgnoreCase)) { throw '应用副本路径检查失败。' }
        if (Test-Path -LiteralPath $copyRoot) { throw '副本目录已存在，请重新运行。' }
        [void][IO.Directory]::CreateDirectory($baseRoot)
        $report.Add('副本位置：' + $copyRoot)
        $report.Add('复制方式：内置 Node.js 逐文件复制，不使用 Robocopy 或 PowerShell 扩展路径枚举')
        Write-Host '[2/3] 正在复制并修复，请稍候……'
        $copiedTree = Invoke-I18nHelper $node $helper 'copy-app' $sourceRoot $copyRoot
        $phase = '核对应用副本'
        $report.Add('副本文件数：' + $copiedTree.files + '；总字节数：' + $copiedTree.bytes)
        if ($copiedTree.manifestHash -ne $sourceTree.manifestHash) { throw '原应用文件清单在复制期间发生变化，请等待原版更新完成后重试。' }
        $copyExe = Join-Path $copyRoot ([IO.Path]::GetFileName($sourceApp.Executable))
        foreach ($relative in @('resources\app.asar', 'ChatGPT.exe', 'Codex.exe')) {
            $file = Join-Path $copyRoot $relative
            if ([IO.File]::Exists($file)) { [IO.File]::SetAttributes($file, ([IO.File]::GetAttributes($file) -band (-bnot [IO.FileAttributes]::ReadOnly))) }
        }
        $marker = @{ tool='tiancai-i18n-2'; source=$sourceRoot; sourceHeaderHash=$inspection.headerHash; version=$inspection.version }
        [IO.File]::WriteAllText((Join-Path $copyRoot '.tiancai-i18n-copy.json'), ($marker | ConvertTo-Json), (New-Object Text.UTF8Encoding($false)))
        $phase = '修复国际化开关'
        $patched = Invoke-I18nHelper $node $helper 'patch-copy' $copyRoot
        $report.Add('国际化修复：' + $patched.patchedGetters + ' 处；文件内容与哈希复核通过')
        $phase = '退出原应用'
        Write-Host '[3/3] 正在设置中文并重启 Codex……'
        $restoreOriginal = $true
        foreach ($process in @(Get-CodexGuiProcesses $sourceApp.Executable)) { try { [void]$process.CloseMainWindow() } catch { } }
        if (-not (Wait-CodexGuiState $sourceApp.Executable $false 15)) {
            $restoreOriginal = $false
            throw '原应用尚未正常退出，未改动语言配置。请先保存文件、结束任务并退出 Codex，再双击此脚本。'
        }
        $phase = '写入语言配置'
        $result = Set-CodexChineseConfig $configPath
        $report.Add('配置文件：' + $configPath)
        $report.Add('语言配置：zh-CN')
        if ($result.Backup) { $report.Add('配置备份：' + $result.Backup) }
        $phase = '启动修复版'
        $userData = Join-Path $baseRoot 'UserData'
        [void][IO.Directory]::CreateDirectory($userData)
        $launcher = New-ChineseCopyLauncher $copyRoot $copyExe $codexHome $userData
        $report.Add('桌面快捷方式：' + $launcher.Shortcut)
        $report.Add('修复版界面数据：' + $userData)
        Start-Process -FilePath (Join-Path $env:WINDIR 'System32\wscript.exe') -ArgumentList ('"' + $launcher.Launcher + '"') -WindowStyle Hidden
        if (-not (Wait-CodexGuiState $copyExe $true 15)) { throw '修复版暂未启动，请查看诊断记录。桌面已保留修复版快捷方式。' }
        $restoreOriginal = $false
        $report.Add('应用启动：已检测到修复副本进程；请人工确认界面')
        Write-Host '修复完成，已打开 Codex，请检查界面是否显示中文。' -ForegroundColor Green
        Write-Host '以后请使用桌面的“Codex 中文修复版（添财AI）”。'
    } catch {
        $exitCode = 1
        Write-Host ('未完成：' + $_.Exception.Message) -ForegroundColor Red
        $report.Add('失败阶段：' + $phase)
        $report.Add('错误：' + $_.Exception.Message)
        if ($copyRoot) { Write-Host ('保留副本用于检查：' + $copyRoot) }
    } finally {
        if ($runtime) {
            try {
                [IO.File]::Delete((Join-Path $runtime.Directory 'repair-i18n.cjs'))
                [IO.File]::Delete($runtime.Executable)
                [IO.Directory]::Delete($runtime.Directory)
            } catch { }
        }
        if ($restoreOriginal -and $sourceApp) {
            try {
                if ($sourceApp.Activation) { Start-Process -FilePath (Join-Path $env:WINDIR 'explorer.exe') -ArgumentList $sourceApp.Activation }
                else { Start-Process -FilePath $sourceApp.Executable }
                Write-Host '已尝试重新打开原版 Codex。'
            } catch { Write-Host '请手动从原来的快捷方式打开 Codex。' }
        }
        try {
            $logRoot = Join-Path $env:LOCALAPPDATA 'TiancaiAI\CodexLocale'
            [void][IO.Directory]::CreateDirectory($logRoot)
            $log = Join-Path $logRoot ('repair-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '-' + [guid]::NewGuid().ToString('N').Substring(0, 6) + '.txt')
            [IO.File]::WriteAllLines($log, $report, (New-Object Text.UTF8Encoding($true)))
            if ($exitCode -ne 0) { Write-Host ('诊断记录：' + $log) }
        } catch { Write-Host '无法写入诊断记录，请保留窗口提示。' }
    }
    return $exitCode
}
if ($MyInvocation.InvocationName -ne '.') { exit (Invoke-CodexChineseRepair) }
